# Generated by Django 6.0.2 on 2026-03-24 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='is_billed',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billed_meter_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BILLED', 'Billed')], default='PENDING', max_length=20),
        ),
    ]
