# Generated by Django 6.0.2 on 2026-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_meterreading_is_billed_meterreading_billed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='amount',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=20),
        ),
    ]
