# Generated by Django 6.0.2 on 2026-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_meterreading_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
