# Generated by Django 6.0.2 on 2026-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_meterreading_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GARBAGE', 'Garbage'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty'), ('OTHER', 'Other'), ('PAYMENT', 'Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringcharge',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GARBAGE', 'Garbage'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty'), ('OTHER', 'Other'), ('PAYMENT', 'Payment')], max_length=20),
        ),
    ]
