# Generated by Django 6.0.2 on 2026-05-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.ledgeraccount')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('NORMAL', 'Normal Credit'), ('DEPOSIT', 'Deposit')], null=True)),
                ('entry_type', models.CharField(choices=[('CHARGE', 'Charge'), ('CREDIT', 'Credit')], max_length=20)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GARBAGE', 'Garbage'), ('SECURITY', 'Security Fee'), ('PARKING', 'Parking Fee'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty'), ('OTHER', 'Other'), ('PAYMENT', 'Payment'), ('REVERSAL', 'Reversal'), ('REFUND', 'Refund')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('reference_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing.invoice')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.ledgeraccount')),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.ledgerentry')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.payment')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_allocations', to='finance.ledgeraccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_allocations', to='finance.payment')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='deposit_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='CreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('NORMAL', 'Normal Credit'), ('DEPOSIT', 'Deposit')], default='NORMAL', max_length=20)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_allocations', to='billing.invoice')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_allocations', to='finance.ledgeraccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='finance.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_credit_allocation'), models.CheckConstraint(condition=models.Q(('amount_applied__gt', 0)), name='credit_allocation_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_allocation'), models.CheckConstraint(condition=models.Q(('amount_applied__gt', 0)), name='payment_allocation_amount_positive')],
            },
        ),
    ]
