# Generated by Django 6.0.2 on 2026-03-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_invoice_category_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GARBAGE', 'Garbage'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty'), ('OTHER', 'Other'), ('PAYMENT', 'Payment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('CHARGE', 'Charge'), ('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal'), ('CREDIT', 'Credit')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_allocation')],
            },
        ),
    ]
