# Generated by Django 6.0.2 on 2026-04-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditallocation',
            name='unique_invoice_allocation',
        ),
        migrations.AddField(
            model_name='creditallocation',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='finance.payment'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='creditallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_credit_allocation'),
        ),
    ]
