# Generated by Django 6.0.2 on 2026-04-04 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_city_property_country_alter_unit_status'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tenant',), name='unique_active_tenancy_per_tenant'),
        ),
    ]
