# Generated by Django 6.0.2 on 2026-04-09 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenancy_unique_active_tenancy_per_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('phone_number', 'landlord'), name='unique_phone_per_landlord'),
        ),
    ]
