# Generated by Django 6.0.2 on 2026-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('VACCANT', 'Vaccant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='VACCANT', max_length=50),
        ),
    ]
